name: server-ci

on:
  pull_request:
    branches: [main]
    paths:
      - "server/**"
      - ".github/workflows/server-ci.yml"

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: server

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: server/go.mod
          cache-dependency-path: server/go.sum

      - name: Echo Go version
        run: go version

      - name: Run tests
        run: go test -covermode=set ./...
